USE [DBPrincipal]
GO

/****** Object:  Table [dbo].[UUSUARIO]    Script Date: 17/08/2021 13:26:38 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PRLA_Usuario](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[NOME] [varchar](200) NOT NULL,
	[CPF] [varchar](200) NOT NULL,
	[EMAIL] [varchar](200) NOT NULL,
	[LOGIN] [varchar](200) NOT NULL,
	[SENHA] [varchar](200) NOT NULL,	
	[DATA_NASCIMENTO] [datetime],
	[STATUS] [bit] NOT NULL Default 1,
	[DATA_CRIACAO][datetime] NOT NULL,
	[USUARIO_CRIACAO] [varchar](200) NOT NULL,
	[DATA_ALTERACAO][datetime] NULL,
	[USUARIO_ALTERACAO] [varchar](200)NULL,
 CONSTRAINT [PRLA_Pk_Usuario] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 80) ON [PRIMARY]
) ON [PRIMARY]
GO


