Create table PRLA_Usuario_Perfil(
ID INT PRIMARY KEY IDENTITY,
ID_USUARIO INT NOT NULL,
ID_PERFIL INT NOT NULL,
STATUS BIT DEFAULT 1 NOT NULL,
DATA_CRIACAO DATETIME NOT NULL,
USUARIO_CRIACAO VARCHAR(200) NOT NULL,
DATA_ALTERACAO DATETIME,
USUARIO_ALTERACAO VARCHAR(200),


CONSTRAINT FK_VINCULO_USUARIO_PERFIL FOREIGN KEY (ID_USUARIO) REFERENCES PRLA_Usuario(ID),
CONSTRAINT FK_VINCULO_PERFIL_USUARIO FOREIGN KEY (ID_PERFIL) REFERENCES PRLA_Perfil(ID)
);